# Default values for mfbackend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
stage: dev

image:
  repository: 192.168.100.73:31003/repository/mydockerrepo/holgerfischer/myfinance-
  pullPolicy: IfNotPresent


pv:
  mntpath: /mnt/data/mf/
  mfdbstorage: /opt/mf
  mfdbpvc: mfdbpvc
  mfdbstoragesize: 5Gi

mfdb:
  db_pw: vulkan
  db_name: mfdb
  db_port: 5432
  db_port_ext: 30023
  db_url: mfdb
