apiVersion: v1
kind: Service
metadata:
 name: {{ .Values.mfdb.db_name }}
spec:
 #this defines which pod is going to be presented by this service
 selector:
  app: {{ .Values.mfdb.db_name }}
 ports:
  - name: {{ .Values.mfdb.db_name }}
    port: 5432
    nodePort: { { .Values.mfdb.db_port_ext } }
 type: NodePort
