#!/usr/bin/env bash

if [ ! -n "${LIQUIBASE_HOME+x}" ]; then
  # echo "LIQUIBASE_HOME is not set."

  ## resolve links - $0 may be a symlink
  PRG="$0"
  while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
    else
    PRG=`dirname "$PRG"`"/$link"
    fi
  done


  LIQUIBASE_HOME=`dirname "$PRG"`

  # make it fully qualified
  LIQUIBASE_HOME=`cd "$LIQUIBASE_HOME" && pwd`
  # echo "Liquibase Home: $LIQUIBASE_HOME"
fi



# add any JVM options here
JAVA_OPTS="${JAVA_OPTS-}"

export PGPASSWORD=$3
until psql "postgresql://$1" -U "$2" -c '\q'; do
	  >&2 echo "Postgres is unavailable - sleeping"
	    sleep 1
    done
    echo "Database available"

#--url=%URL% --username=%USER% --password=%PW%
if [ ! $# -eq 3 ]
then
echo "please add the arguments url, username and password, only these and in the right order."
echo "E.G: liquibase localhost:5432/marketdata_dev postgres pw "
else
java -cp "$LIQUIBASE_HOME/liquibase-core-3.5.3.jar:$LIQUIBASE_HOME/postgresql-42.2.2.jar" $JAVA_OPTS liquibase.integration.commandline.Main  --driver=org.postgresql.Driver --changeLogFile=$LIQUIBASE_HOME/changelog/changelog-master.xml --url="jdbc:postgresql://$1" --username=$2 --password=$3 update
fi
